### ISSUE TITLE
can you make it work in the PC Version?

### ISSUE THREAD

**Issue by thephazze** [AdamBadagliacco/THPS-Career-Lvl-100-Automation#1]
Hi, thanks for doing this, looks like a great tool for the last achievement.

Not sure if you can make it compatible or maybe add another version.
I tried with the PC version and only change stance.

The movement keys are:
W -> Dpad Up
S -> Dpad Down
A -> Dpad Left
D -> Dpad Right

And for the tricks

Left Arrow Keyboard -> Square
Right Arrow Keyboard -> Circle 
Up Arrow Keyboard -> Triangle
Down Arrow Keyboard -> X or Cross

ESC-> This is pause
Space -> Jump

Thanks again for this amazing tool!
Have a good day!

**Comment by thephazze** [comment]
I did some modifications to my keyboard buttons and it works all except the PAUSE button.

if you change the buttons to the image and modify the code in line 34
to this it works perfectly

            PressButton(simulator, VirtualKeyCode.ESCAPE); //Pause Game
![imagen](https://github.com/AdamBadagliacco/THPS-Career-Lvl-100-Automation/assets/38045300/6dc489ec-0388-4a3d-b622-63641a4f4f76)

Thanks again

**Comment by AdamBadagliacco** [comment]
I'm thrilled that what I made was useful to you in getting the last achievement!

It seems like you were able to get it working for PC without my help. Thanks for documenting the steps in these comments. I'm going to attach a link in the original YouTube video to your comments in case it helps out any future PC users.
