### ISSUE TITLE
[Documentation] Requires WindowsInput and InputSimulator nuget packages

### ISSUE THREAD

**Issue by circlesaucer** [AdamBadagliacco/THPS-Career-Lvl-100-Automation#2]
I think this is probably self-explanatory for better programmers, but is something small that I struggled with. 

If you want to build this EXE on your own, it requires the [WindowsInput ](https://www.nuget.org/packages/WindowsInput) and [InputSimulator](https://www.nuget.org/packages/InputSimulator) nuget packages. I immediately added WindowsInput, but spent a half hour playing around until I realized that InputSimulator is its own nuget package. 

This issue is purely for documentation purposes. Maybe this could be included in the readme for ease of use? 

Otherwise thanks for much for this! I had to update the timings a bit, but after that it worked flawlessly on PS4 and PC!

**Comment by AdamBadagliacco** [comment]
It took a surprisingly long amount of time to put together the video and documentation for this project, so I'm really happy to hear it was useful to you!

I have updated the readme as you suggested, thank you for that improvement.
